### ISSUE TITLE
(Feature) Launch automated tests 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard-test-automation#1]
@vbaranov @fernandomg 
Test can be launched by API request:
``` 
curl -u a1a9a14f4c1cb8c71dc0c3b0df3be1cc53f2303b: \
     -d build_parameters[CIRCLE_JOB]=build \
     https://circleci.com/api/v1.1/project/github/poanetwork/token-wizard-test-automation/tree/master
```
Please,add launching of it to [npm test script of Token wizard]( https://github.com/poanetwork/token-wizard/blob/7e4db13c9be8fc65b19bf78d0c6c3787f985e6d3/package.json#L116)

**Comment by vbaranov** [comment]
@dennis00010011b I still can't add this utility to token-wizard. There are errors in automated test. Please take a look at the attached log:
[token-wizard.log](https://github.com/poanetwork/token-wizard-test-automation/files/1758012/token-wizard.log)

I launched the last version from master branch with `npm run test1`.

**Comment by vbaranov** [comment]
@dennis00010011b you can close it.
