### ISSUE TITLE
(Fix) change network to Sokol

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard-test-automation#6]
Let's change networkID to Sokol network (`77`) to increase speed of tests

**Comment by dennis00010011b** [comment]
There is option to set up network in user's configuration file  https://github.com/poanetwork/token-wizard-test-automation/blob/master/users/user77_27F2.json
Network's codes:
0: Classic, the (un)forked public Ethereum Classic main network
3: Ropsten, the public cross-client Ethereum testnet
4: Rinkeby, the public Geth PoA testnet
42: Kovan, the public Parity PoA testnet
77: Sokol, the public POA Network testnet, https://sokol.poa.network
99: Core, the public POA Network main network,https://core.poa.network
8545:localhost8545

**Comment by vbaranov** [comment]
@dennis00010011b can we close it? It seems we already changed to Sokol.
